export const agentsData = [
  {
    id: 1,
    fullName: "David Gamboa",
    name: "Hassel",
    status: "Alive",
    location: "Venezuela",
    specialty: "Espionage",
    affiliation: "Tukis",
    languages: "English, Spanish",
    imageUrl: "david_gamboa4.png",
    imageLargeUrl: "david_gamboa2.png",
  },
  {
    id: 2,
    fullName: "Tomas Mejia",
    name: "Eicos",
    status: "Alive",
    location: "Argentina",
    specialty: "Software Sabotage",
    affiliation: "Tukis",
    languages: "English, Japanese",
    imageUrl: "tomas_mejia4.png",
    imageLargeUrl: "tomas_mejia2.png",
  },
  {
    id: 3,
    fullName: "Daniel Millan",
    name: "Daniel",
    status: "Alive",
    location: "Uruguay",
    specialty: "CQC, Sharpshooter",
    affiliation: "Tukis",
    languages: "English, Spanish",
    imageUrl: "daniel_millan4.png",
    imageLargeUrl: "daniel_millan2.png",
  },
  {
    id: 4,
    fullName: "Sebastian Rodriguez",
    name: "Nefer",
    status: "Alive",
    location: "Canada",
    specialty: "Reconnaissance",
    affiliation: "Tukis",
    languages: "English, French",
    imageUrl: "sebastian_rodriguez4.png",
    imageLargeUrl: "sebastian_rodriguez2.png",
  },
  {
    id: 5,
    fullName: "Edward Chamorro",
    name: "DJMisterpeluca",
    status: "Dead",
    location: "Portugal",
    specialty: "Being Dead",
    affiliation: "Tukis",
    languages: "English, Portuguese",
    imageUrl: "ale2.png",
    imageLargeUrl: "ale2.png",
  },
  {
    id: 6,
    fullName: "Octavio Mendez",
    name: "Jugo",
    status: "Alive",
    location: "Uruguay",
    specialty: "Survivalism",
    affiliation: "La C",
    languages: "English, French",
    imageUrl: "octavio_mendez2.png",
    imageLargeUrl: "octavio_mendez2.png",
  },
  {
    id: 8,
    fullName: "Fabrizio Brandani",
    name: "Fabrizio",
    status: "Alive",
    location: "Spain",
    specialty: "Gun Expert",
    affiliation: "La Boulangerie",
    languages: "Spanish, Portuguese",
    imageUrl: "fabrizio_brandani2.png",
    imageLargeUrl: "fabrizio_brandani2.png",
  },
  {
    id: 9,
    fullName: "Unknown",
    name: "Unknown",
    status: "Unknown",
    location: "Unknown",
    specialty: "Being Unknown",
    affiliation: "Unknown",
    languages: "Unknownese",
    imageUrl: "unknown2.png",
    imageLargeUrl: "unknown2.png",
  },
  {
    id: 10,
    fullName: "Unknown",
    name: "Unknown",
    status: "Unknown",
    location: "Unknown",
    specialty: "Being Unknown",
    affiliation: "Unknown",
    languages: "Unknownese",
    imageUrl: "unknown2.png",
    imageLargeUrl: "unknown2.png",
  },
  {
    id: 11,
    fullName: "Unknown",
    name: "Unknown",
    status: "Unknown",
    location: "Unknown",
    specialty: "Being Unknown",
    affiliation: "Unknown",
    languages: "Unknownese",
    imageUrl: "unknown2.png",
    imageLargeUrl: "unknown2.png",
  },
];